/**
 * German translations
 */
import { Translations } from './types';

const de: Translations = {
  // General app keys
  'app.title': 'Blame Game',
  'app.footer': '© 2025 Blame Game',
  'app.back': 'Zurück',
  'app.next': 'Weiter',
  'app.save': 'Speichern',
  'app.cancel': 'Abbrechen',
  'app.loading': 'Wird geladen...',
  
  // Common keys
  'common.back': 'Zurück',
  'common.next': 'Weiter',
  
  // Intro screen
  'intro.start_game': 'Spiel starten',
  'intro.player_setup': 'Spieler einrichten',
  'intro.settings': 'Einstellungen',
  'intro.info': 'Info',
  'intro.sound_toggle': 'Sound',
  'intro.name_blame_toggle': 'NameBlame Modus',
  'intro.name_blame_mode': 'NameBlame Modus',
  'intro.name_blame_explanation': 'Im NameBlame-Modus wird jede Frage nur einmal gezeigt. Der aktive Spieler wählt wen er beschuldigt. Der beschuldigte Spieler liest die Frage vor und wird zum nächsten aktiven Spieler.',
  'intro.enable_debug': 'Debug-Modus aktivieren',
  'intro.heading': 'Wem traust du was zu?',
  'intro.subheading': 'Was denkst du? Wer würde was tun?',
  'intro.tagline': 'Wem traust du was zu?',
  'intro.main_question': 'Wer würde am ehesten...',
  'intro.subtitle': 'Was denkst du? Kennst du deine Freunde?',
  'intro.error_loading_questions': 'Fehler beim Laden der Fragen:',
  'intro.error_check_files': 'Bitte überprüfe die Fragen-Datei und versuche es erneut.',
  'intro.loading_questions': 'Fragen werden geladen...',
  'intro.mainTitle': 'Wer würde was tun?',
  'intro.subTitle': 'Was denkst du? Wer würde am ehesten...',
  'intro.who_would': 'Wer würde am ehesten...',
  'intro.select_categories': 'Manuelle Kategorieauswahl',

  // Category pick screen
  'category_pick.title': 'Kategorien auswählen',
  'category_pick.confirm': 'Mit {{count}} Kategorien starten',
  'category_pick.back': 'Zurück',
  'category_pick.questions_available': '{{count}} Fragen',
  'category_pick.max_categories': 'Maximal {{count}} Kategorien',
  'category_pick.selected_count': '{{count}} ausgewählt',

  // Settings
  'settings.title': 'Einstellungen',
  'settings.game_settings': 'Spiel-Einstellungen',
  'settings.content_settings': 'Inhalt-Einstellungen',
  'settings.game_behavior': 'Spiel-Verhalten',
  'settings.experience': 'Spielerlebnis',
  // Dynamic UI groups
  'settings.group.content': 'Inhalt',
  'settings.group.behavior': 'Verhalten',
  'settings.group.experience': 'Spielerlebnis',
  'settings.group.general': 'Allgemein',
  'settings.no_dynamic_fields': 'Keine dynamischen Einstellungen definiert. Standardwerte werden verwendet.',
  'settings.categories_per_game': 'Kategorien pro Spiel',
  'settings.questions_per_category': 'Fragen pro Kategorie',
  'settings.max_questions_total': 'Max. Fragen insgesamt',
  'settings.allow_repeat_questions': 'Fragen wiederholen erlauben',
  'settings.shuffle_questions': 'Fragen mischen',
  'settings.shuffle_categories': 'Kategorien mischen',
  'settings.allow_skip_questions': 'Fragen überspringen erlauben',
  'settings.show_progress': 'Fortschritt anzeigen',
  'settings.enable_sounds': 'Sounds aktivieren',
  'settings.enable_animations': 'Animationen aktivieren',
  'settings.reset': 'Zurücksetzen',
  'settings.language': 'Sprache',
  'settings.sound': 'Sound',
  'settings.sound_on': 'Sound aktivieren',
  'settings.sound_off': 'Sound stumm schalten',
  'settings.volume': 'Lautstärke',
  'settings.animations': 'Animationen',
  'settings.reset_data': 'App-Daten zurücksetzen',
  'settings.dark_mode': 'Zum Dunklen Modus wechseln',
  'settings.light_mode': 'Zum Hellen Modus wechseln',
  'settings.theme': 'Design',

  // Player setup
  'players.setup_title': 'Spieler einrichten',
  'players.add_player': 'Spieler hinzufügen',
  'players.player_name': 'Spielername',
  'players.player_name_input': 'Spielername eingeben',
  'players.start_game': 'Spiel starten',
  'players.back': 'Zurück',
  'players.max_players': 'Maximale Spieleranzahl erreicht!',
  'players.min_players': 'Mindestens 3 Spieler erforderlich',
  'players.min_players_nameblame_hint': 'Du brauchst mindestens 3 Spieler für den NameBlame Modus.',
  'players.name_required': 'Name erforderlich',
  'players.name_exists': 'Name existiert bereits',
  'players.remove': 'Entfernen',
  'players.remove_player': 'Spieler {name} entfernen',
  'players.add_players_to_start': 'Füge Spieler hinzu, um zu starten',
  'players.minimum_players_needed': 'Du brauchst mindestens 2 Spieler, um zu starten',
  
  // Loading screen
  'loading.defaultQuote': 'Wird geladen...',
  'loading.preparing': 'Vorbereitung läuft...',
  'loading.preparing_game': 'Spiel wird vorbereitet...',

  // Categories
  'categories.Beim Feiern': 'Beim Feiern',
  'categories.In Beziehungen': 'In Beziehungen',
  'categories.Bei der Arbeit': 'Bei der Arbeit',
  'categories.In der Schule': 'In der Schule',
  'categories.In peinlichen Momenten': 'In peinlichen Momenten',
  'categories.Im Urlaub': 'Im Urlaub',
  'categories.Beim Sport': 'Beim Sport',
  'categories.In der Freundschaft': 'In der Freundschaft',
  'categories.Im Alltag': 'Im Alltag',
  'categories.In der Familie': 'In der Familie',
  'categories.In der Zukunft': 'In der Zukunft',
  'categories.Beim Essen': 'Beim Essen',
  'categories.Im Bad': 'Im Bad',
  'categories.Im Internet': 'Im Internet',
  'categories.Im Straßenverkehr': 'Im Straßenverkehr',
  'categories.Bei Filmen & Serien': 'Bei Filmen & Serien',
  'categories.In der WG': 'In der WG',
  'categories.Beim Flirten': 'Beim Flirten',
  'categories.Auf Partys mit Fremden': 'Auf Partys mit Fremden',
  'categories.Beim Weltuntergang': 'Beim Weltuntergang',
  'categories.Im Paralleluniversum': 'Im Paralleluniversum',
  'categories.Im Land der schlechten Entscheidungen': 'Im Land der schlechten Entscheidungen',
  'categories.Im inneren Monolog': 'Im inneren Monolog',
  
  // Game
  'game.question': 'Frage',
  'game.select_player': 'Wähle einen Spieler',
  'game.next_question': 'Nächste Frage',
  'game.previous_question': 'Vorherige Frage',
  'game.progress': 'Frage {current} von {total}',
  'game.blame': 'Schuld geben',
  'game.summary': 'Zusammenfassung',
  'game.play_again': 'Nochmal spielen',

  // Questions (Added missing keys with German placeholders)
  'question.player_turn': 'Dein Zug',
  'question.counter': 'Frage {{current}} von {{total}}',
  'questions.counter': 'Frage {{current}} von {{total}}',
  'question.who_blame': 'Wen beschuldigst du?',
  'question.cannot_blame_self': 'Du kannst dich nicht selbst beschuldigen',
  'question.blame_player': 'Beschuldige {{name}}',
  'question.blamed_you_for': '{{name}} hat dich beschuldigt für',
  'question.next_blame': 'Weiter',
  'question.previous_question': 'Zurück',
  'question.next_question': 'Weiter',
  'question.summary': 'Zusammenfassung',
  'question.next': 'Weiter',
  'question.show_summary': 'Zusammenfassung anzeigen',
  'question.select_player': 'Wähle einen Spieler',
  'question.progress': 'Frage {{current}} von {{total}}',
  'question.view_results': 'Ergebnisse anzeigen',
  'question.blame_revealed': 'Schuld zugeschoben!',
  'question.was_blamed': 'wurde beschuldigt',
  
  // Summary
  'summary.title': 'Danke fürs Spielen!',
  'summary.game_over': 'Spiel beendet!',
  'summary.game_complete': 'Spiel beendet!',
  'summary.thanks_for_playing': 'Danke fürs Spielen!',
  'summary.questions_answered': 'Fragen beantwortet',
  'summary.questions_completed': 'Ihr habt {count} Fragen gemeistert!',
  'summary.most_blamed': 'Am meisten beschuldigt',
  'summary.most_blamed_player': 'Am meisten beschuldigter Spieler',
  'summary.most_blamed_singular': 'Meistbeschuldigter',
  'summary.most_blamed_plural': 'Meistbeschuldigte',
  'summary.blame_count': '{{count}} Beschuldigung{{s}}',
  'summary.blamed_count': '{{count}} Beschuldigung{{s}}',
  'summary.plural_suffix': 'en',
  'summary.no_blames_given': 'Keine Beschuldigungen verteilt!',
  'summary.team_round': 'Team-Runde',
  'summary.team_message': '{{activePlayersCount}} Spieler',
  'summary.players': 'Spieler',
  'summary.new_game': 'Neues Spiel starten',
  'summary.play_again': 'Nochmal spielen',
  'summary.back_to_start': 'Zurück zum Start',
  'summary.blame_stats': 'Blame-Statistik',
  'summary.blame_statistics': 'Blame-Statistik',
  'summary.recent_blames': 'Letzte Aktivität',
  'summary.no_stats': 'Keine Beschuldigungen verteilt!',
  
  // Blame notifications
  'blame.notification_title': 'Beschuldigung aufgezeichnet!',
  'blame.blamed_player_for': 'beschuldigte',
  'blame.notification_for_blamed': 'Du wurdest von {{blamer}} beschuldigt!',
  'blame.continue_to_next': 'Weiter zum nächsten Spieler',
  'blame.continue_to_question': 'Weiter zur nächsten Frage',
  'blame.round_complete': 'Alle Spieler haben beschuldigt - weiter zur nächsten Frage',
  'blame.already_blamed_this_round': '{player} hat bereits in dieser Runde beschuldigt',
  
  // Modal
  'modal.info_title': 'Information',
  'modal.info_description': 'Das Spielprinzip ist einfach: Du gibst der Person das Handy, welche am besten zur Frage passt. Die Person liest ihre Frage vor, erklärt sich oder gibt das Handy schnell mit der nächsten Karte weiter.',
  'modal.reset_data_description': 'Aktuell dient diese Seite hauptsächlich zum Zurücksetzen der App-Daten. \nMade with ❤️ by bziuk.com.',
  'modal.close': 'Schließen',
  'modal.reset_app_data': 'App-Daten zurücksetzen',

  // Info section/modal (Added missing keys with German placeholders)
    // Info section/modal
  'info.title': 'Information',
  'info.how_to_play': 'So spielt man Blame Game',
  'info.name_blame_explanation': 'Im NameBlame-Modus kannst du andere Spieler beschuldigen',
  'info.confirm_reset': 'Bist du sicher, dass du alle App-Daten zurücksetzen möchtest?',

  // Debug panel (Added missing keys with German placeholders)
  'debug.panel_title': 'Debug Panel',
  'debug.title': 'Debug Panel Titel',
  'debug.question_stats': 'Fragen-Statistik',
  'debug.total': 'Gesamt',
  'debug.played': 'Gespielt',
  'debug.available': 'Verfügbar',
  'debug.categories': 'Kategorien',
  'debug.reset': 'Zurücksetzen',
  'debug.reset_all_settings': 'Alle Einstellungen zurücksetzen',
  'debug.reset_app_data': 'App-Daten zurücksetzen',
  'debug.confirm_reset_data': 'Bist du sicher, dass du ALLE App-Daten zurücksetzen möchtest? Dies umfasst Einstellungen und gespielte Fragen.',
  'debug.settings': 'Einstellungen (Debug)',
  'debug.questions': 'Fragen (Debug)',
  'debug.animations': 'Animationen (Debug)',
  'debug.language': 'Sprache (Debug)',
  'debug.reset_data': 'Daten zurücksetzen (Debug)',

  // Footer
  'footer.support_message': 'Unterstütze uns für mehr Spiele!',
  'footer.donate_message': 'Deine Spende hilft uns, bessere Spiele zu entwickeln.',

  // Additional keys
  'startGame': 'Spiel starten',
  'error.loadQuestions': 'Fehler beim Laden der Fragen. Bitte überprüfen Sie die Fragendateien und versuchen Sie es erneut.',
  'loadingQuestions': 'Fragen werden geladen...',
  'error.noQuestionsLoaded': 'Keine Fragen geladen. Bitte überprüfen Sie die Fragendateien und versuchen Sie es erneut.',

  // Custom categories
  'custom_categories.title': 'Benutzerdefinierte Kategorien',
  'custom_categories.manage': 'Kategorien verwalten',
  'custom_categories.add_category': 'Kategorie hinzufügen',
  'custom_categories.edit_category': 'Kategorie bearbeiten',
  'custom_categories.delete_category': 'Kategorie löschen',
  'custom_categories.category_name': 'Kategoriename',
  'custom_categories.emoji': 'Emoji',
  'custom_categories.questions': 'Fragen',
  'custom_categories.add_question': 'Frage hinzufügen',
  'custom_categories.edit_question': 'Frage bearbeiten',
  'custom_categories.delete_question': 'Frage löschen',
  'custom_categories.question_text': 'Fragentext',
  'custom_categories.no_categories': 'Noch keine benutzerdefinierten Kategorien. Erstelle eine, um loszulegen!',
  'custom_categories.no_questions': 'Noch keine Fragen. Füge einige Fragen zu dieser Kategorie hinzu!',
  'custom_categories.confirm_delete_category': 'Möchtest du diese Kategorie wirklich löschen? Alle Fragen gehen verloren.',
  'custom_categories.confirm_delete_question': 'Möchtest du diese Frage wirklich löschen?',
  'custom_categories.create_new': 'Neue Kategorie erstellen',
  'custom_categories.save': 'Speichern',
  'custom_categories.cancel': 'Abbrechen',
  'custom_categories.placeholder_name': 'Kategorienamen eingeben',
  'custom_categories.placeholder_emoji': 'Emoji auswählen',
  'custom_categories.placeholder_question': 'Wer würde am ehesten...',
  'custom_categories.question_count': '{{count}} Frage(n)',
  'custom_categories.select_emoji': 'Emoji auswählen',
  'custom_categories.success_created': 'Kategorie erfolgreich erstellt!',
  'custom_categories.success_updated': 'Kategorie erfolgreich aktualisiert!',
  'custom_categories.success_deleted': 'Kategorie erfolgreich gelöscht!',
  'custom_categories.error_name_required': 'Kategoriename ist erforderlich',
  'custom_categories.error_emoji_required': 'Emoji ist erforderlich',
  'custom_categories.error_question_required': 'Fragentext ist erforderlich'
};

export default de;
