// Loading quotes displayed during the roulette/loading screen

export const LOADING_QUOTES = [
  "Kalibriere Schuldzuweisung...",
  "Scanne Ausreden...",
  "Berechne Ironie-Level...",
  "Wer hat's wieder getan?",
  "Fingerzeigen initialisiert...",
  "Lade neue Ausreden herunter...",
  "Verstecke Beweise...",
  "Schiebe Schuld auf den Nachbarn...",
  "Zähle leere Versprechungen...",
  "Analysiere peinliche Stille...",
  "Suche nach dem Sündenbock...",
  "Würfle Verantwortlichkeiten...",
  "Lade Alibi-Updates...",
  "Synchronisiere Ausflüchte...",
  "Verteile schwarze Peter...",
  "Finde den, der zuletzt gelacht hat...",
  "Überprüfe Ausreden-Datenbank...",
  "Starte Schuldumkehr-Prozess...",
  "Erstelle Notlügen...",
  "Warte auf Geständnisse...",
  "Zufällige Schuld wird verteilt...",
  "Lade Meme für die Ausrede...",
  "Wer war's diesmal wirklich?",
  "Schuldfrage wird verschoben...",
  "Lade Kaffee für die Diskussion...",
];
